name = "Cobblemon Modpack"
author = "Julian"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "58b560003dad0ab329f0d6e902e197269654231e97b39a8af1796e97e9840d22"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.255"
