name = "Cobblemon Modpack"
author = "Julian"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bc0f37b91a2729d51a6b298eb32e9c13532ff3fd0acf5bc9e8431d91b76c0a26"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.255"
